### PR TITLE
Port linqtotwitter library and unit tests to .NET Standard to support .NET Core.

### PR DESCRIPTION
**Pull request by Dixin**
Port library to .NET Standard, so that it supports .NET Core and other platforms.

Port unit tests too. Existing unit tests and ported unit tests passes. Also manually tested the library. A few API calls in unit test code cannot be compiled with .NET Standard, so added conditional compilation symbol NETCORE.

### CODE REVIEW

**Comment by JoeMayo** [comment]
Was this built with VS 2017 RC? I doesn't load in VS 2015.

**Comment by Dixin** [comment]
Yes. VS 2015 uses .xproj and project.json files for .NET Core projects, as a result, .NET Core projects cannot use your shared projects, and cannot add file links. To make it work in VS 2015, all source files and test code have to be copied to the .NET Core projects.

VS 2017 supports .csproj for .NET Core projects. I used your shared projects to build the library, and I created unit test project by simply include your current test code.

**Comment by Dixin** [comment]
Great. Can you also update the nuget package?

**Comment by JoeMayo** [comment]
I just pushed a beta version to NuGet: https://www.nuget.org/packages/linqtotwitter/4.2.0-beta1

**Pull request merged**
