### PR TITLE
Adding an issue template

### PR DESCRIPTION
**Pull request by JeepNL**
An issue template where users can fill in some basic info about their configuration.

### CODE REVIEW

**Comment by JeepNL** [comment]
Maybe this is an idea to add when users submit a new issue, so we know their basic configuration. 

Please check my English / Grammer 😉 and add any other changes if necessary.

**Comment by JeepNL** [comment]
Template looks like this: 

----

**Please let us know what you use:**

1. .NET SDK version:
2. LINQ To Twitter Version:
3. Twitter API version (v1/v2) 👇
  * [ ] V1 
  * [ ] V2
    * [ ] Essential access 
    * [ ] Elevated access 
    * [ ] Academic research access

ℹ Use [x] to select

----

**Describe the issue**
A clear and concise description of what the issue is.


**If applicable, add the error result**

----

**Comment by JeepNL** [comment]
For the V2 API we need to know if they've configured their app as a **Public Client** or **Confidential** Client too.

**Type op App:** 

- [ ] Public Client (_Native App / Single Page App_)
- [ ] Confidential Client (_Web App / Automated App or Bot_)

**Review by JoeMayo — APPROVED** [review]
Nice - Thanks!

**Pull request merged**
